import { Employee, AbsenceRequest, Document } from '@/types';

export const employees: Employee[] = [
  {
    id: '1',
    name: 'Sofia Ribeiro',
    email: 'sofia.ribeiro@hrvision.com',
    role: 'CEO',
    department: 'Engineering',
    status: 'Active',
    avatar: 'https://picsum.photos/seed/1/100/100',
    hireDate: '2020-01-15',
    salary: 150000,
    phone: '(11) 98765-4321',
    address: 'Rua das Flores, 123, São Paulo, SP',
    bank: 'Banco Vision',
    bankAgency: '0001',
    bankAccount: '12345-6',
  },
  {
    id: '2',
    name: 'Arthur Costa',
    email: 'arthur.costa@hrvision.com',
    role: 'Head of Engineering',
    department: 'Engineering',
    status: 'Active',
    avatar: 'https://picsum.photos/seed/2/100/100',
    managerId: '1',
    hireDate: '2020-02-20',
    salary: 120000,
    phone: '(11) 98765-4322',
    address: 'Av. Paulista, 456, São Paulo, SP',
    bank: 'Banco Vision',
    bankAgency: '0001',
    bankAccount: '23456-7',
  },
  {
    id: '3',
    name: 'Julia Martins',
    email: 'julia.martins@hrvision.com',
    role: 'Frontend Developer',
    department: 'Engineering',
    status: 'Active',
    avatar: 'https://picsum.photos/seed/3/100/100',
    managerId: '2',
    hireDate: '2021-07-01',
    salary: 80000,
    phone: '(11) 98765-4323',
    address: 'Rua Augusta, 789, São Paulo, SP',
    bank: 'Banco Vision',
    bankAgency: '0001',
    bankAccount: '34567-8',
  },
  {
    id: '4',
    name: 'Lucas Almeida',
    email: 'lucas.almeida@hrvision.com',
    role: 'Backend Developer',
    department: 'Engineering',
    status: 'On Leave',
    avatar: 'https://picsum.photos/seed/4/100/100',
    managerId: '2',
    hireDate: '2021-07-01',
    salary: 85000,
    phone: '(11) 98765-4324',
    address: 'Rua da Consolação, 101, São Paulo, SP',
    bank: 'Banco Vision',
    bankAgency: '0001',
    bankAccount: '45678-9',
  },
  {
    id: '5',
    name: 'Isabella Ferreira',
    email: 'isabella.ferreira@hrvision.com',
    role: 'Head of Marketing',
    department: 'Marketing',
    status: 'Active',
    avatar: 'https://picsum.photos/seed/5/100/100',
    managerId: '1',
    hireDate: '2020-03-10',
    salary: 110000,
    phone: '(21) 91234-5678',
    address: 'Av. Rio Branco, 202, Rio de Janeiro, RJ',
    bank: 'Banco Vision',
    bankAgency: '0001',
    bankAccount: '56789-0',
  },
  {
    id: '6',
    name: 'Davi Santos',
    email: 'davi.santos@hrvision.com',
    role: 'Marketing Analyst',
    department: 'Marketing',
    status: 'Active',
    avatar: 'https://picsum.photos/seed/6/100/100',
    managerId: '5',
    hireDate: '2022-01-20',
    salary: 70000,
    phone: '(21) 91234-5679',
    address: 'Rua do Ouvidor, 303, Rio de Janeiro, RJ',
    bank: 'Banco Vision',
    bankAgency: '0001',
    bankAccount: '67890-1',
  },
  {
    id: '7',
    name: 'Laura Oliveira',
    email: 'laura.oliveira@hrvision.com',
    role: 'Head of Sales',
    department: 'Sales',
    status: 'Active',
    avatar: 'https://picsum.photos/seed/7/100/100',
    managerId: '1',
    hireDate: '2020-04-01',
    salary: 115000,
    phone: '(31) 98888-7777',
    address: 'Av. Afonso Pena, 404, Belo Horizonte, MG',
    bank: 'Banco Vision',
    bankAgency: '0001',
    bankAccount: '78901-2',
  },
  {
    id: '8',
    name: 'Bernardo Pereira',
    email: 'bernardo.pereira@hrvision.com',
    role: 'Sales Representative',
    department: 'Sales',
    status: 'Active',
    avatar: 'https://picsum.photos/seed/8/100/100',
    managerId: '7',
    hireDate: '2022-05-15',
    salary: 75000,
    phone: '(31) 98888-7778',
    address: 'Rua da Bahia, 505, Belo Horizonte, MG',
    bank: 'Banco Vision',
    bankAgency: '0001',
    bankAccount: '89012-3',
  },
  {
    id: '9',
    name: 'Manuela Rodrigues',
    email: 'manuela.rodrigues@hrvision.com',
    role: 'Head of Design',
    department: 'Design',
    status: 'Active',
    avatar: 'https://picsum.photos/seed/9/100/100',
    managerId: '1',
    hireDate: '2020-06-01',
    salary: 110000,
    phone: '(41) 99999-8888',
    address: 'Rua XV de Novembro, 606, Curitiba, PR',
    bank: 'Banco Vision',
    bankAgency: '0001',
    bankAccount: '90123-4',
  },
  {
    id: '10',
    name: 'Heitor Azevedo',
    email: 'heitor.azevedo@hrvision.com',
    role: 'UI/UX Designer',
    department: 'Design',
    status: 'Terminated',
    avatar: 'https://picsum.photos/seed/10/100/100',
    managerId: '9',
    hireDate: '2021-11-11',
    salary: 78000,
    phone: '(41) 99999-8889',
    address: 'Alameda Dr. Muricy, 707, Curitiba, PR',
    bank: 'Banco Vision',
    bankAgency: '0001',
    bankAccount: '01234-5',
  },
];

export const absenceRequests: AbsenceRequest[] = [
  {
    id: 'req1',
    employeeId: '3',
    type: 'Vacation',
    startDate: '2024-09-16',
    endDate: '2024-09-20',
    status: 'Approved',
  },
  {
    id: 'req2',
    employeeId: '4',
    type: 'Sick Leave',
    startDate: '2024-08-19',
    endDate: '2024-08-23',
    status: 'Approved',
    reason: 'Flu',
  },
  {
    id: 'req3',
    employeeId: '6',
    type: 'Vacation',
    startDate: '2024-10-07',
    endDate: '2024-10-11',
    status: 'Pending',
  },
  {
    id: 'req4',
    employeeId: '8',
    type: 'Personal',
    startDate: '2024-08-26',
    endDate: '2024-08-26',
    status: 'Denied',
    reason: 'Team deadline',
  },
];

export const documents: Document[] = [
  {
    id: 'doc1',
    name: 'ID_Card.pdf',
    type: 'Identification',
    uploadDate: '2021-07-01',
    url: '#',
  },
  {
    id: 'doc2',
    name: 'Proof_of_Address.pdf',
    type: 'Address',
    uploadDate: '2021-07-01',
    url: '#',
  },
  {
    id: 'doc3',
    name: 'Employment_Contract.pdf',
    type: 'Contract',
    uploadDate: '2021-07-01',
    url: '#',
  },
];
